version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node-backend-img
    container_name: portfolio-backend-container
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./:/usr/src/app
      #- /usr/src/app/node_modules
      - ./public:/usr/src/app/public
    ports:
      - "8000:8000"
    env_file: ./.env
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  admin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8082:8082"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8082
    networks:
      - app-network

  nginx:
    depends_on:
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - app-network
    ports: 
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  jenkins_home:
  node_modules:
  web-root:
    driver: local
